export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAIL = 'GET_TODOS_FAIL';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAIL = 'EDIT_TODO_FAIL';

export const GET_TODO_DETAILS_REQUEST = 'GET_TODO_DETAILS_REQUEST';
export const GET_TODO_DETAILS_SUCCESS = 'GET_TODO_DETAILS_SUCCESS';
export const GET_TODO_DETAILS_FAIL = 'GET_TODO_DETAILS_FAIL';
export const GET_TODO_DETAILS_RESET = 'GET_TODO_DETAILS_RESET';

export const UPDATE_STATUS_TODO_REQUEST = 'UPDATE_STATUS_TODO_REQUEST';
export const UPDATE_STATUS_TODO_SUCCESS = 'UPDATE_STATUS_TODO_SUCCESS';
export const UPDATE_STATUS_TODO_FAIL = 'UPDATE_STATUS_TODO_FAIL';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';
